import React, { useState, useCallback, useMemo } from 'react';
import QRCode from 'qrcode.react';
import Button from '@material-ui/core/Button';
import { createTOTPToken, loginWithTOTP } from '../lib/authentication';

export default function OTPManagement() {
  const [otpUrl, setOtpUrl] = useState('');
  const [tmpToken, setTmpToken] = useState('');
  const setUpTOTPDevice = useCallback(async () => {
    try {
      const { otp_url, tmp_token } = await createTOTPToken();
      setOtpUrl(otp_url);
      setTmpToken(tmp_token);
    } catch (error) {
      console.error(error);
    }
  }, [])

  const [userCode, setUserCode] = useState('');
  const onUserCodeChange = (event) => setUserCode(event.target.value);
  const onValidateTOTP = useCallback(async () => {
    try {
      const response = await loginWithTOTP(tmpToken, userCode);
      console.log(response);
    } catch (error) {
      console.error(error);
    }
  })

  return (
    <>
      <div>
        <Button variant="contained" onClick={setUpTOTPDevice}>Setup a new TOTP device</Button>
      </div>
      {otpUrl && (
        <div>
          <QRCode value={otpUrl} />
        </div>
      )}
      {tmpToken && (
        <>
          <div>
            TMP token: {tmpToken}
          </div>
          <div>
            <input
              value={userCode}
              onChange={onUserCodeChange}
              type="text"
              placeholder="Code generated by your app"
            />
            <button onClick={onValidateTOTP}>Validate</button>
          </div>
        </>
      )}
    </>
  )
}